# Generated by Django 4.2.16 on 2026-07-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0002_hospitaladminprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospital",
            name="verified",
        ),
    ]
