# Generated by Django 4.2.16 on 2026-07-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0003_remove_hospital_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorprofile",
            name="verified",
        ),
    ]
