# Generated by Django 4.2.16 on 2026-07-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0004_remove_doctorprofile_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
