# Generated by Django 4.2.16 on 2026-06-29 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0002_hospitaladminprofile"),
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="hospitals.hospital",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[("ADD_RECORD", "Add Record"), ("VIEW_RECORD", "View Record")],
                max_length=30,
            ),
        ),
    ]
