# Generated by Django 4.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="hospital_address",
            field=models.TextField(
                blank=True,
                null=True,
                help_text="Hospital address at the time of visit"
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="reason_for_visit",
            field=models.TextField(
                blank=True,
                null=True,
                help_text="Chief complaint or reason for this visit"
            ),
        ),
    ]
